- fix regression with postgres11 undefined method `[]' for DBI::Type::Varchar:Class (NoMethodError)
git-svn-id: svn+ssh://svn.freebsd.org/ports/head@521934 35697150-7ecd-e111-bb59-0022644237b5