graphics/qt5-wayland: unbreak with libglvnd after r557300
Checking for Linux dma-buf Buffer Sharing... no
Checking for Linux Client dma-buf Buffer Sharing... no
Checking for Linux dma-buf Buffer Sharing... no
[...]
executing config test dmabuf-server-buffer
+ cd /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-server-buffer && /usr/local/lib/qt5/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared warn_off console single_arch" 'QMAKE_USE += egl' /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-server-buffer
+ cd /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-server-buffer && MAKEFLAGS= make
> clang++ -c -pipe -O2 -w -fPIC  -I. -I/usr/local/include -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o main.o main.cpp
> main.cpp:4:10: fatal error: 'drm_fourcc.h' file not found
> #include <drm_fourcc.h>
>          ^~~~~~~~~~~~~~
> 1 error generated.
> *** Error code 1
> Stop.
> make[2]: stopped in /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-server-buffer
test config.qtwayland_client.tests.dmabuf-server-buffer FAILED
[...]
executing config test dmabuf-client-buffer
+ cd /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-client-buffer && /usr/local/lib/qt5/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared warn_off console single_arch" 'QMAKE_USE += egl' /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-client-buffer
+ cd /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-client-buffer && MAKEFLAGS= make
> clang++ -c -pipe -O2 -w -fPIC  -I. -I/usr/local/include -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o main.o main.cpp
> main.cpp:4:10: fatal error: 'drm_mode.h' file not found
> #include <drm_mode.h>
>          ^~~~~~~~~~~~
> 1 error generated.
> *** Error code 1
> Stop.
> make[2]: stopped in /wrkdirs/usr/ports/graphics/qt5-wayland/work/qtwayland-everywhere-src-5.15.2/config.tests/dmabuf-client-buffer
test config.qtwayland_compositor.tests.dmabuf-client-buffer FAILED
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%QT_CMAKEDIR%%/Qt5WaylandClient/Qt5WaylandClient_DmaBufServerBufferPlugin.cmake
Error: Missing: %%QT_CMAKEDIR%%/Qt5WaylandCompositor/Qt5WaylandCompositor_DmaBufServerBufferIntegrationPlugin.cmake
Error: Missing: %%QT_CMAKEDIR%%/Qt5WaylandCompositor/Qt5WaylandCompositor_QWaylandDmabufClientBufferIntegrationPlugin.cmake
Error: Missing: %%QT_PLUGINDIR%%/wayland-graphics-integration-client/libdmabuf-server.so
Error: Missing: %%QT_PLUGINDIR%%/wayland-graphics-integration-server/libqt-wayland-compositor-dmabuf-server-buffer.so
Error: Missing: %%QT_PLUGINDIR%%/wayland-graphics-integration-server/libqt-wayland-compositor-linux-dmabuf-unstable-v1.so
===> Error: Plist issues found.
*** Error code 1


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@558191 35697150-7ecd-e111-bb59-0022644237b5