www/squid: fix build on GCC architectures
Add --disable-strict-error-checking to CONFIGURE_ARGS for everyone. It adds -Werror, which is against ports tree policy and causes:
Icmp6.cc: In member function 'virtual void Icmp6::SendEcho(Ip::Address&, int, const char*, int)':
Icmp6.cc:165:72: error: converting a packed 'icmp6_hdr' pointer (alignment 1) to a 'short unsigned int' pointer (alignment 2) may result in an unaligned pointer value [-Werror=address-of-packed-member]
  165 |     icmp->icmp6_cksum = CheckSum((unsigned short *) icmp, icmp6_pktsize);
      |                                                                        ^
In file included from Icmp6.h:20,
                 from Icmp6.cc:18:
/usr/include/netinet/icmp6.h:72:8: note: defined here
   72 | struct icmp6_hdr {
      |        ^~~~~~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-deprecated-register' [-Werror]
cc1plus: all warnings being treated as errors

PR:		241804
Approved by:	timp87@gmail.com (maintainer), mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@519101 35697150-7ecd-e111-bb59-0022644237b5