Update to Wine 5.17.  This includes the following changes:  - ADVAPI32 library converted to PE.  - Beginnings of an NDIS network driver.  - Still more restructuration of the console support.  - Various bug fixes.
The Wine Staging patchset for this release is broken on FreeBSD and/or
with GCC 9, so mark this option as broken:

file.c:237:37: error: 'EXTATTR_NAMESPACE_USER' undeclared (first use in this fun
ction)
  237 |     return extattr_get_fd( filedes, EXTATTR_NAMESPACE_USER, &name[XATTR_
USER_PREFIX_LEN],
file.c:237:67: error: 'XATTR_USER_PREFIX_LEN' undeclared (first use in this func
tion); did you mean 'XATTR_USER_PREFIX'?
  237 |     return extattr_get_fd( filedes, EXTATTR_NAMESPACE_USER, &name[XATTR_
USER_PREFIX_LEN],


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@548471 35697150-7ecd-e111-bb59-0022644237b5