sysutils/opencorsairlink: fix build on GCC architectures
Linking to libm is required to build this port with GCC:
/wrkdirs/usr/ports/sysutils/opencorsairlink/work/OpenCorsairLink-4234f4f/protocol/rmi/core.c:49: undefined reference to `pow'

PR:		241457
Approved by:	linimon (mentor), lifanov (maintainer timeout)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@516979 35697150-7ecd-e111-bb59-0022644237b5