Mark BROKEN: fails to build
INFO: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /wrkdirs/usr/ports/science/py-tensorflow-estimator/work/bazel_out/d73ee990c0bb8c7712db2655de14c420/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /wrkdirs/usr/ports/science/py-tensorflow-estimator/work/bazel_out/d73ee990c0bb8c7712db2655de14c420/external/bazel_tools/tools/build_defs/repo/utils.bzl:169:9
 - /DEFAULT.WORKSPACE.SUFFIX:276:1
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip failed: class java.net.ConnectException Can't assign requested address (connect failed)
WARNING: Download from https://github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip failed: class java.net.ConnectException Can't assign requested address (connect failed)
ERROR: An error occurred during the fetch of repository 'rules_cc':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip, https://github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip] to /wrkdirs/usr/ports/science/py-tensorflow-estimator/work/bazel_out/d73ee990c0bb8c7712db2655de14c420/external/rules_cc/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip: Can't assign requested address (connect failed)
ERROR: /wrkdirs/usr/ports/science/py-tensorflow-estimator/work/bazel_out/d73ee990c0bb8c7712db2655de14c420/external/bazel_tools/tools/launcher/BUILD:11:1: @bazel_tools//tools/launcher:launcher depends on @bazel_tools//src/tools/launcher:launcher in repository @bazel_tools which failed to fetch. no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip, https://github.com/bazelbuild/rules_cc/archive/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip] to /wrkdirs/usr/ports/science/py-tensorflow-estimator/work/bazel_out/d73ee990c0bb8c7712db2655de14c420/external/rules_cc/0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip: Can't assign requested address (connect failed)
ERROR: Analysis of target '//tensorflow_estimator/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@518016 35697150-7ecd-e111-bb59-0022644237b5