net/mDNSResponder: fix build on GCC architectures
Error:
../mDNSCore/DNSCommon.c:3636: error: 'for' loop initial declaration used outside C99 mode

But USE_CSTD=c99 causes another problem:
../mDNSCore/DNSDigest.c:958:9: warning: implicit declaration of function 'asm' is invalid in C99 [-Wimplicit-function-declaration]
        R0(A,B,C,D,X[ 0], 7,0xd76aa478L);
        ^

Just use newer GCC.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@527053 35697150-7ecd-e111-bb59-0022644237b5