security/heaan: fix build on GCC architectures
Patch created manually, because WRKSRC differs.
Add include sys/time.h:
In file included from ../src/TestScheme.cpp:20:
../src/TimeUtils.h:20:17: error: field 'startTime' has incomplete type 'timeval'
   20 |  struct timeval startTime, stopTime;
      |                 ^~~~~~~~~

MFH:		2020Q4 (fix build blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@552103 35697150-7ecd-e111-bb59-0022644237b5