textproc/qr: fix build on GCC architectures
sqrt() is only defined since C99:
/tmp/ccn0UwwD.o:(.text+0x1cc): undefined reference to `sqrt'

MFH:		2020Q3 (fix build blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@546122 35697150-7ecd-e111-bb59-0022644237b5