audio/opusfile: Fix QA issues
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/COPYING
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.

http://package21.nyi.freebsd.org/data/114amd64-default-qat/566258/logs/errors/opusfile-0.12.log


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@566483 35697150-7ecd-e111-bb59-0022644237b5