devel/py-meliae: update to 0.5.1
This version uses Python 3 so undeprecate the port. Limit it up to
Python 3.8 as it fails to compile on Python 3.9:

meliae/_scanner.c:3388:46: error: use of undeclared identifier 'PyGC_Head'
  __pyx_t_1 = __Pyx_PyInt_FromSize_t((sizeof(PyGC_Head))); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 52, __pyx_L1_error)
                                             ^

Comment out the license file as it is not shipped in the distribution.

PR:		249642
Submitted by:	swills
Approved by:	maintainer timeout (sbz, 1 month)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@555635 35697150-7ecd-e111-bb59-0022644237b5