games/lugaru: fix build on GCC architectures
New OpenAL requires C++11:
/usr/local/lib/libopenal.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@519147 35697150-7ecd-e111-bb59-0022644237b5