Add USE_CSTD=c99 to fix regression on GCC-based systems:
  ../bin/dconf.c:136: error: 'for' loop initial declaration used outside C99 mode

Approved by:	maintainer


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@539355 35697150-7ecd-e111-bb59-0022644237b5