games/xcowsay: fix build on GCC architectures
Use C99 instead of the default C89:
bubblegen.c:186: error: 'for' loop initial declaration used outside C99 mode


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@526317 35697150-7ecd-e111-bb59-0022644237b5