biology/mummer: fix build on powerpc64 elfv2 and powerpc64le
Error:
src/tigr/postnuc.cc:174:37: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        Alignments.push_back({ *Mp, CurrCp->dirB } );

Since it may also fix runtime issues on powerpc64 elfv1, bump PORTREVISION.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@553298 35697150-7ecd-e111-bb59-0022644237b5