devel/py-fastprogress: Not compatible with Python 2
Missing dependency (configparser) and invalid syntax.

File "/usr/local/lib/python2.7/site-packages/fastprogress/fastprogress.py", line 72
    end = '' if len(self.comment) == 0 else f' {self.comment}'
SyntaxError: invalid syntax

File "/usr/local/lib/python2.7/site-packages/fastprogress/core.py", line 10
    if h!= 0: return f'{h}:{m:02d}:{s:02d}'
SyntaxError: invalid syntax

Reported by:	pkg-fallout
Approved by:	portmgr blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@545464 35697150-7ecd-e111-bb59-0022644237b5