emulators/yuzu: unbreak on FreeBSD < 12 after r552531
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2u", but required is at least "1.1" (found /usr/lib/libcrypto.so, )
CMake Error at externals/CMakeLists.txt:83 (add_subdirectory):

In file included from src/core/hle/service/bcat/backend/boxcat.cpp:6:
externals/./httplib/httplib.h:214:2: error: Sorry, OpenSSL versions prior to 1.1.1 are not supported
 #error Sorry, OpenSSL versions prior to 1.1.1 are not supported
  ^

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@555685 35697150-7ecd-e111-bb59-0022644237b5