sysutils/pacman: Unbreak build on FreeBSD >= 12.1
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to MD5_Final
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to MD5_Init
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to MD5_Update
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to SHA256_Final
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to SHA256_Init
ld: error: ../../lib/libalpm/.libs/libalpm.so: undefined reference to SHA256_Update

http://beefy6.nyi.freebsd.org/data/121amd64-default/529299/logs/errors/pacman-5.1.3.log

Add missing -lcrypto to SSL_LIBS and make sure libalpm is linked
directly with it instead of indirectly through dependencies.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529787 35697150-7ecd-e111-bb59-0022644237b5