According to pkg-fallout 11.3-RELEASE-p7 runs into problems building dlls/dbghelp/module.c after upstream changes in the last two weeks due to a specific combination of macros related to ELF being (not) defined:
  module.c: In function 'image_locate_build_id_target':
  module.c:643:32: error: 'NT_GNU_BUILD_ID' undeclared (first use in this function)
    643 |                 if (note[2] == NT_GNU_BUILD_ID)
        |                                ^~~~~~~~~~~~~~~

Add a patch that I created and provided upstream where it was tentatively
ack-ed already.

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529780 35697150-7ecd-e111-bb59-0022644237b5