deskutils/foliate: fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/locale/eu/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Error: Orphaned: share/locale/nb/LC_MESSAGES/com.github.johnfactotum.Foliate.mo
Error: Orphaned: share/locale/nn/LC_MESSAGES/com.github.johnfactotum.Foliate.mo


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@557073 35697150-7ecd-e111-bb59-0022644237b5