games/devilutionX: Unbreak after r525796
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /applications/devilutionx.desktop
Error: Orphaned: /icons/hicolor/16x16/apps/devilutionx.png
Error: Orphaned: /icons/hicolor/32x32/apps/devilutionx.png
Error: Orphaned: /icons/hicolor/48x48/apps/devilutionx.png

http://package21.nyi.freebsd.org/data/113amd64-default-qat/526187/logs/devilutionX-1.0.0.log

Pointy hat:	0mp


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@526476 35697150-7ecd-e111-bb59-0022644237b5