sysutils/flowgger: Update to 0.2.9
This also unbreaks the build with rust-nightly:
error[E0214]: parenthesized type parameters may only be used with a `Fn` trait
  --> /wrkdirs/usr/ports/sysutils/flowgger/work/flowgger-0.2.6-28-gab572a0/cargo-crates/twox-hash-1.1.0/src/number_streams.rs:67:23
   |
67 |     fn count(self) -> usize() {
   |                       ^^^^^^^ only `Fn` traits may use parentheses
...
74 | number_stream!(U32FromBytes, u32, U32_BYTES);
   | --------------------------------------------- in this macro invocation

error[E0214]: parenthesized type parameters may only be used with a `Fn` trait
  --> /wrkdirs/usr/ports/sysutils/flowgger/work/flowgger-0.2.6-28-gab572a0/cargo-crates/twox-hash-1.1.0/src/number_streams.rs:67:23
   |
67 |     fn count(self) -> usize() {
   |                       ^^^^^^^ only `Fn` traits may use parentheses
...
75 | number_stream!(U64FromBytes, u64, U64_BYTES);
   | --------------------------------------------- in this macro invocation

error: aborting due to 2 previous errors

- Take it back
- Upstream repo is now awslabs/flowgger
- Switch to crates.io since releases are no longer tagged on GitHub
- Update WWW


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@523933 35697150-7ecd-e111-bb59-0022644237b5