security/nss: fix build with GCC architectures
-Werror=unused-function causes:
verified/kremlin/kremlib/dist/minimal/FStar_UInt128.h:82:37: error: 'FStar_UInt128_mul32' declared 'static' but never defined [-Werror=unused-function]
   82 | inline static FStar_UInt128_uint128 FStar_UInt128_mul32(uint64_t x, uint32_t y);

Add -Wno-error=unused-function to fix build.

Approved by:	portmgr (ports tree compliance)
MFH:		2020Q1 (ports tree compliance)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@526016 35697150-7ecd-e111-bb59-0022644237b5