multimedia/ffmpeg: explicitly depend on cairo
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/libavcodec.so.58.91.100 is linked to /usr/local/lib/libcairo.so.2 from graphics/cairo but it is not declared as a dependency
Warning: you need USE_GNOME+=cairo
Warning: Possible REINPLACE_CMD issues

$ rg cairo
configure
6255:enabled librsvg           && require_pkg_config librsvg librsvg-2.0 librsvg-2.0/librsvg/rsvg.h rsvg_handle_render_cairo

doc/Doxyfile
2247:# Possible values are: png, png:cairo, png:cairo:cairo, png:cairo:gd, png:gd,
2248:# png:gd:gd, jpg, jpg:cairo, jpg:cairo:gd, jpg:gd, jpg:gd:gd, gif, gif:cairo,
2249:# gif:cairo:gd, gif:gd, gif:gd:gd and svg.

libavcodec/librsvgdec.c
43:    cairo_surface_t *image;
44:    cairo_t *crender = NULL;
77:    image = cairo_image_surface_create_for_data(frame->data[0], CAIRO_FORMAT_ARGB32,
80:    if (cairo_surface_status(image) != CAIRO_STATUS_SUCCESS)
83:    crender = cairo_create(image);
85:    cairo_save(crender);
86:    cairo_set_operator(crender, CAIRO_OPERATOR_CLEAR);
87:    cairo_paint(crender);
88:    cairo_restore(crender);
90:    cairo_scale(crender, dimensions.width / (double)unscaled_dimensions.width,
93:    rsvg_handle_render_cairo(handle, crender);
95:    cairo_destroy(crender);
96:    cairo_surface_destroy(image);


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@539347 35697150-7ecd-e111-bb59-0022644237b5