devel/gitlab-runner: unbreak on aarch64
  # github.com/kr/pty
  vendor/github.com/kr/pty/pty_freebsd.go:50:20: undefined: fiodgnameArg
  vendor/github.com/kr/pty/pty_freebsd.go:63:12: undefined: _C_SPECNAMELEN
  vendor/github.com/kr/pty/pty_freebsd.go:66:9: undefined: fiodgnameArg

Add the missing ztypes_freebsd_arm64.go file for aarch64

  # golang.org/x/sys/unix
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

Import upstream patch https://github.com/golang/sys/commit/33540a1f603772f9d4b761f416f5c10dade23e96

PR:		245012
Approved by:	swills (maintainer), manu (mentor, implicit)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529268 35697150-7ecd-e111-bb59-0022644237b5