graphics/shaderc: use upstream repo in case the fork is deleted
As of 2020.0 the workaround is still required without LLD such as on
DragonFly or FreeBSD < 12:

FAILED: glslc/glslc
: && /usr/bin/c++  -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -Wimplicit-fallthrough -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -fstack-protector-strong -L/usr/local/lib glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o  -o glslc/glslc  glslc/libglslc.a  libshaderc_util/libshaderc_util.a  libshaderc/libshaderc.a  libshaderc_util/libshaderc_util.a  -lSPIRV-Tools-opt  -lSPIRV-Tools  -lHLSL  -lglslang  -lOSDependent  -lOGLCompiler  -lglslang  -lOSDependent  -lOGLCompiler  -lSPIRV  -pthread && :
/usr/local/lib/libglslang.a(ShaderLang.cpp.o): In function `(anonymous namespace)::CreateBuiltInParseables(TInfoSink&, glslang::EShSource)':
ShaderLang.cpp:(.text+0x7502): undefined reference to `glslang::TBuiltInParseablesHlsl::TBuiltInParseablesHlsl()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@536039 35697150-7ecd-e111-bb59-0022644237b5